AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  duckdb-static-bundle-example

  SAM Template for duckdb-static-bundle-example

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 5
    MemorySize: 128
    Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
      Variables:
        S3_ENDPOINT: "ltbase.dev:19000"
        S3_OBJECT_URI: "s3://ltbase-dev/yellow_tripdata_2024-01.parquet"
        AWS_ACCESS_KEY_ID: "s3_local_access_key"
        AWS_SECRET_ACCESS_KEY: "s3_local_secret_key"
        AWS_REGION: "us-west-2"
        S3_URL_STYLE: "path"
        S3_USE_SSL: "false"
    # You can add LoggingConfig parameters such as the Logformat, Log Group, and SystemLogLevel or ApplicationLogLevel. Learn more here https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/sam-resource-function.html#sam-function-loggingconfig.
    LoggingConfig:
      LogFormat: JSON
Resources:
  DuckDBExampleFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Metadata:
      BuildMethod: makefile
    Properties:
      CodeUri: .
      Handler: bootstrap
      Runtime: provided.al2023
      Architectures:
        - arm64 
      Events:
        HttpProxy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY


Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  LocalApiEndpoint:
    Description: Invoke URL for the SAM local API Gateway emulator.
    Value: http://127.0.0.1:3000
